### ISSUE TITLE
Build a CI pipeline for this project

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/jodie#4]
A CI Pipeline using GitHub actions should be built that at least executes the unit test on each pull request created.

**Comment by brayanjuls** [comment]
I was thinking initially of something simple, like this:

```
name: Jodie CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test
 ```
